import React, { createContext, useContext, useState, useEffect } from 'react';
import { translateFormData } from '../services/translationService';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

// Translation dictionary
const translations = {
en: {
  // Header
  'header.home': 'Home',
  'header.create': 'Create',
  'header.saved': 'Saved',
  'header.logout': 'Logout',
  'header.login': 'Login',

  // Home Page
  'home.title': 'ABBK PhysicsWorks',
  'home.subtitle': 'Fiche Generator Platform',
  'home.description': 'Professional Document Generation System',
  'home.createTitle': 'Create a New Fiche',
  'home.createDesc': 'Generate professional training and installation documents using our guided wizard.',
  'home.createFeature1': 'Training programs',
  'home.createFeature2': 'License installations',
  'home.createFeature3': 'Ready-to-export PDF format',
  'home.getStarted': 'Get Started',
  'home.savedTitle': 'Saved Fiches',
  'home.savedDesc': 'Access, download, and manage all your previously generated documents.',
  'home.savedFeature1': 'Search and filter',
  'home.savedFeature2': 'Download PDFs',
  'home.savedFeature3': 'Edit and regenerate',
  'home.viewArchive': 'View Archive',
  'home.whyChoose': 'Why Choose ABBK Fiche Generator?',
  'home.professionalTitle': 'Professional Templates',
  'home.professionalDesc': 'Industry-standard document formats for training and installation',
  'home.easyTitle': 'Easy to Use',
  'home.easyDesc': 'A step-by-step wizard guides you through the entire process',
  'home.cloudTitle': 'Cloud Storage',
  'home.cloudDesc': 'Access your documents anywhere, anytime with secure cloud storage',
  'home.totalSteps': 'Total Steps',
  'home.documentTypes': 'Document Types',
  'home.exportFormat': 'Export Format',
  'home.needHelp': 'Need Help?',
  'home.helpDesc': 'Contact our support team for help with document generation.',

  // Progress Bar
  'progress.contact': 'Contact',
  'progress.intervention': 'Intervention',
  'progress.preview': 'Preview',
  'progress.plan': 'Plan',
  'progress.presence': 'Attendance',
  'progress.evaluation': 'Evaluation',
  'progress.current': 'Current',
  'progress.formationPack': 'Training Pack',
  'progress.inProgress': 'In Progress',

  // Navigation Buttons
  'nav.back': 'Back',
  'nav.next': 'Next',
  'nav.downloadPdf': 'Download PDF',
  'nav.generating': 'Generating...',
  'nav.generateFichePlan': 'Generate Training Plan',
  'nav.generatingPlan': 'Generating Plan...',
  'nav.generateFichePresence': 'Generate Attendance Sheet',
  'nav.completePack': 'Complete Training Pack',
  'nav.completingPack': 'Completing Pack...',
  'nav.continueTo': 'Continue to',
  'nav.saveFinish': 'Save & Finish Later',
  'nav.continueFromSaved': 'You can continue this pack from the Saved page',

  // Step 1 - Client Selection
  'step1.title': 'CLIENT SELECTION',
  'step1.search': 'Search by ID or Name...',
  'step1.addClient': 'Add New Client',
  'step1.newClient': 'New Client',
  'step1.companyName': 'Company Name',
  'step1.matriculeFiscal': 'Tax ID (Matricule Fiscal)',
  'step1.address': 'Address',
  'step1.phone': 'Phone',
  'step1.contactInfo': 'Contact Information',
  'step1.selectClient': 'Select Client:',
  'step1.selectPlaceholder': '-- Select a client --',
  'step1.clientName': 'Client Name:',
  'step1.clientId': 'Client ID:',
  'step1.selectToContinue': 'Select a client to continue',
  'step1.searchOrAdd': 'Search by ID/Name or add a new client',
  'step1.clientsFound': 'client(s) found',
  'step1.fillRequired': 'Please fill in Name and Tax ID',
  'step1.clientAdded': '✅ Client added successfully!',
  'step1.loading': 'Loading clients...',
  'step1.noClientsFound': 'No clients found matching:',
  'step1.matriculeFiscal': 'Tax ID',

  // Step 2 - Intervention Type
  'step2.title': 'INTERVENTION TYPE',
  'step2.selectType': 'Select intervention type',
  'step2.formations': 'Trainings',
  'step2.allSoftware': 'All Software',
  'step2.selectFormations': 'Select one or more trainings',
  'step2.selected': 'training(s) selected',
  'step2.unsavedChanges': '⚠️ Unsaved changes',
  'step2.customFormation': 'Custom',
  'step2.editAllFields': 'Custom training - All fields editable',
  'step2.templateModify': 'Template - You can modify and save as new',
  'step2.saveChanges': 'Save Changes?',
  'step2.saveMessage': 'You have modified this training. What would you like to do?',
  'step2.saveAsNew': 'Save as New Training',
  'step2.useWithoutSaving': 'Use Without Saving',
  'step2.formationSaved': 'Training saved successfully!',
  'step2.changesDiscarded': 'Changes discarded',
  'step2.saveNote': '* Saving creates a new custom training with your modifications',
  'step2.unsavedWarning': 'You have unsaved changes. Continue without saving?',
  'step2.formationOrLicense': 'Training or License',
  'step2.selectToView': 'Select a training to view and edit details',
  'step2.fieldsPreFilled': 'All fields are pre-filled but can be modified',
  'error.loadingFormations': 'Error loading trainings',
  'error.savingFormation': 'Error saving training',
  'step2.license': 'License',
  'step2.licenseInfo': 'Select one or more licenses to install',
  'step2.formationName': 'Training Name',
  'step2.reference': 'Reference',
  'step2.prerequisites': 'Prerequisites',
  'step2.objectives': 'Objectives',
  'step2.competencies': 'Competencies',
  'step2.schedule': 'Schedule',
  'step2.days': 'Days',
  'step2.content': 'Content',
  'step2.methods': 'Methods',
  'step2.addDay': 'Add Day',

  // Step 3 - Common Details
  'step3.title': 'Intervention Details',
  'step3.nature': 'Nature of the intervention:',
  'step3.observations': 'Observations:',
  'step3.referenceBC': 'Reference BC:',
  'step3.date': 'Intervention Date:',
  'step3.intervenant': 'Intervenant(s):',
  'step3.selectIntervenant': '-- Select an Intervenant --',
  'step3.location': 'Made in (Location):',
  'step3.autoGenerated': '(Auto-generated)',
  'step3.naturePlaceholder': 'Describe the intervention',
  'step3.observationsPlaceholder': 'Additional notes or remarks',
  'step3.referencePlaceholder': 'Reference BC',
  'step3.locationPlaceholder': 'e.g., Ariana, Tunis',

  // Step 4 - Preview
  'step4.title': 'Preview',
  'step4.preview': 'Fiche Preview',
  'step4.formationTitle': 'TRAINING PROGRAM SHEET',
  'step4.licenseTitle': 'INSTALLATION SHEET',
  'step4.client': 'Client:',
  'step4.address': 'Address:',
  'step4.phone': 'Phone:',
  'step4.id': 'ID:',
  'step4.formationName': 'Training Name:',
  'step4.reference': 'Reference:',
  'step4.prerequisites': 'Prerequisites',
  'step4.objectives': 'Objectives',
  'step4.competencies': 'Acquired Competencies',
  'step4.schedule': 'Training Schedule',
  'step4.days': 'Days',
  'step4.content': 'Content / Concepts',
  'step4.methods': 'Methods',
  'step4.duration': 'Duration (Hours)',
  'step4.theory': 'Theory',
  'step4.practice': 'Practice',
  'step4.totalTheory': 'Total Theory:',
  'step4.totalPractice': 'Total Practice:',
  'step4.total': 'Total:',
  'step4.licenseInstalled': 'Installed License(s)',
  'step4.quantity': 'Quantity',
  'step4.serialNumber': 'Serial Number',
  'step4.invoiceNumber': 'Invoice Number',
  'step4.noLicenses': 'No licenses added',
  'step4.intervenants': 'Intervenant(s)',
  'step4.interventionDate': 'Intervention Date',
  'step4.interventionNumber': 'Intervention Number',
  'step4.madeAt': 'Made at:',
  'step4.clientRemarks': 'Client Remarks:',
  'step4.clientSignature': 'Client Signature:',
  'step4.intervenantSignature': 'Intervenant Signature:',
  'step4.date': 'Date:',
  'step4.footer': '© 2025 ABBK PHYSICSWORKS.',

  // Step 5 - Training Plan
  'step5.title': 'TRAINING PLAN SHEET',
  'step5.step': 'Step 5 of 7',
  'step5.subtitle': 'Step 5 of 7',
  'step5.clientSummary': 'Client Summary',
  'step5.client': 'Client:',
  'step5.location': 'Location:',
  'step5.intervenant': 'Intervenant:',
  'step5.formationsPlanning': 'Training Plan',
  'step5.addFormation': 'Add Training',
  'step5.formation': 'Training',
  'step5.formateur': 'Trainer',
  'step5.nombreJours': 'Number of Days',
  'step5.duree': 'Duration',
  'step5.lieu': 'Location',
  'step5.dateDebut': 'Start Date',
  'step5.dateFin': 'End Date',
  'step5.heures': 'Hours',
  'step5.details': 'Details',
  'step5.note': 'Note:',
  'step5.contactNote': 'Contact Note:',
  'step5.dateLe': 'Dated:',
  'step5.signature': 'Signature',
  'step5.signatureABBK': 'ABBK PHYSICSWORKS Signature',

  // Step 6 - Attendance Sheet
  'step6.title': 'ATTENDANCE SHEET',
  'step6.step': 'Step 6 of 7',
  'step6.entreprise': 'Company:',
  'step6.theme': 'Training Theme:',
  'step6.periode': 'Training Period:',
  'step6.heure': 'Training Hours:',
  'step6.cadre': 'Training Framework:',
  'step6.nombreJours': 'Number of Training Days (max 7):',
  'step6.lieu': 'Training Location:',
  'step6.formateur': 'Trainer:',
  'step6.duree': 'Training Duration:',
  'step6.mode': 'Training Mode:',
  'step6.participants': 'List of Participants',
  'step6.addParticipant': 'Add Participant',
  'step6.nomPrenom': 'Full Name',
  'step6.etablissement': 'Institution / Company',
  'step6.jours': 'Days',
  'step6.details': 'Details',
  'step6.note': 'Note:',
  'step6.dateLe': 'Dated:',
  'step6.signature': 'Signature',
  'step6.signatureFormateur': 'Trainer Signature',
  'step6.signatureABBK': 'ABBK PHYSICSWORKS Signature',

  // Step 7 - Evaluation
  'step7.title': 'EVALUATION SHEET',
  'step7.subtitle': 'PARTICIPANT FEEDBACK',
  'step7.step': 'Step 7 of 7 - Final Step!',
  'step7.theme': 'Training Theme:',
  'step7.periode': 'Training Period:',
  'step7.duree': 'Training Duration:',
  'step7.formateur': 'Trainer:',
  'step7.participants': 'List of Participants',
  'step7.infoNiveau': 'Level Information',
  'step7.niveauInitial': 'Initial Level',
  'step7.connaissances': 'Theoretical Knowledge',
  'step7.competencesPratiques': 'Practical Skills',
  'step7.participation': 'Participation & Engagement',
  'step7.niveauParticipation': 'Level of Active Participation',
  'step7.contribution': 'Contribution to Discussions',
  'step7.comprehension': 'Understanding of Content',
  'step7.bonneComprehension': 'Demonstrated Good Understanding',
  'step7.capaciteAppliquer': 'Ability to Apply Knowledge',
  'step7.niveauCompetences': 'Level of Technical Skills Acquired',
  'step7.attitude': 'General Attitude During Training',
  'step7.ponctuel': 'Was the participant punctual and consistent?',
  'step7.amelioration': 'Showed significant improvement during training',
  'step7.noteGeneral': 'Overall Score',
  'step7.note': 'Note:',
  'step7.dateLe': 'Dated:',
  'step7.signatureFormateur': 'Trainer Signature',
  'step7.signatureABBK': 'ABBK PHYSICSWORKS Signature',

  // Saved Page
  'saved.title': 'Saved Fiches',
  'saved.found': 'fiches found',
  'saved.refresh': 'Refresh',
  'saved.search': 'Search by client name, ID, or filename...',
  'saved.allTypes': 'All Types',
  'saved.formationOnly': 'Training Only',
  'saved.licenseOnly': 'License Only',
  'saved.loading': 'Loading fiches...',
  'saved.noFiches': 'No fiches found',
  'saved.tryAdjusting': 'Try adjusting your search or filters',
  'saved.createFirst': 'Create your first fiche to get started!',
  'saved.formation': 'Training',
  'saved.license': 'License',
  'saved.formations': 'Trainings:',
  'saved.licenses': 'Licenses:',
  'saved.edit': 'Edit',
  'saved.delete': 'Delete fiche',
  'saved.confirmDelete': 'Are you sure you want to delete this fiche?',

  // Common
  'common.client': 'Client',
  'common.address': 'Address',
  'common.phone': 'Phone',
  'common.cancel': 'Cancel',
  'common.save': 'Save',
  'common.close': 'Close',
  'common.loading': 'Loading...',
  'common.error': 'Error',
  'common.success': 'Success',
  'common.required': 'required',
  'common.generated': 'Generated',

  // Errors
  'error.fillRequired': 'Please complete all required fields',
  'error.fixErrors': 'Please fix the errors before continuing',
  'error.selectClient': 'Please select a client from the dropdown',
  'error.selectType': 'Please select an intervention type (Training or License)',
  'error.enterReference': 'Please enter Reference BC',
  'error.selectDate': 'Please select an intervention date',
  'error.selectIntervenant': 'Please select an intervenant',
  'error.enterLocation': 'Please enter a location (Made in)',
  'error.fillFormationName': 'Please fill in at least one training name',
  'error.addParticipant': 'Please add at least one participant',
  'error.evaluationMissing': 'Evaluation data is missing',

  // Nav additional
    'nav.continueTo': 'Continue to',
    'nav.saveFinish': 'Save & Finish Later',
    'nav.continueFromSaved': 'You can continue this pack from the Saved page',
    'common.generated': 'Generated',
    'step1.noAddPermission': 'You cannot add new clients. Contact an administrator.',
'step2.noSavePermission': 'You can modify formations for your fiche, but cannot save them permanently. Contact an administrator.',
'permissions.noAccess': 'You do not have permission to perform this action.',
'permissions.adminRequired': 'Administrator access required.',
'permissions.superadminRequired': 'Superadmin access required.',
},

  fr: {
    // Header
    'header.home': 'Accueil',
    'header.create': 'Créer',
    'header.saved': 'Enregistrés',
    'header.logout': 'Déconnexion',
    'header.login': 'Connexion',
    
    // Home Page
    'home.title': 'ABBK PhysicsWorks',
    'home.subtitle': 'Plateforme de Génération de Fiches',
    'home.description': 'Système Professionnel de Génération de Documents',
    'home.createTitle': 'Créer une Nouvelle Fiche',
    'home.createDesc': 'Générez des documents professionnels de formation et d\'installation avec notre assistant guidé.',
    'home.createFeature1': 'Programmes de formation',
    'home.createFeature2': 'Installations de licences',
    'home.createFeature3': 'Export PDF prêt',
    'home.getStarted': 'Commencer',
    'home.savedTitle': 'Fiches Enregistrées',
    'home.savedDesc': 'Accédez, téléchargez et gérez tous vos documents précédemment générés.',
    'home.savedFeature1': 'Recherche et filtrage',
    'home.savedFeature2': 'Télécharger les PDFs',
    'home.savedFeature3': 'Modifier et régénérer',
    'home.viewArchive': 'Voir les Archives',
    'home.whyChoose': 'Pourquoi Choisir le Générateur de Fiches ABBK?',
    'home.professionalTitle': 'Modèles Professionnels',
    'home.professionalDesc': 'Formats de documents standard pour les formations et installations',
    'home.easyTitle': 'Facile à Utiliser',
    'home.easyDesc': 'L\'assistant étape par étape vous guide tout au long du processus',
    'home.cloudTitle': 'Stockage Cloud',
    'home.cloudDesc': 'Accédez à vos documents n\'importe où, n\'importe quand avec un stockage cloud sécurisé',
    'home.totalSteps': 'Étapes Totales',
    'home.documentTypes': 'Types de Documents',
    'home.exportFormat': 'Format d\'Export',
    'home.needHelp': 'Besoin d\'Aide?',
    'home.helpDesc': 'Contactez notre équipe d\'assistance pour la génération de documents',
    
    // Progress Bar
    'progress.contact': 'Contact',
    'progress.intervention': 'Intervention',
    'progress.preview': 'Aperçu',
    'progress.plan': 'Plan',
    'progress.presence': 'Présence',
    'progress.evaluation': 'Évaluation',
    'progress.current': 'Actuel',
    'progress.formationPack': 'Pack de Formation ',
    'progress.inProgress': 'En Cours',
    
    // Navigation Buttons
    'nav.back': 'Retour',
    'nav.next': 'Suivant',
    'nav.downloadPdf': 'Télécharger PDF',
    'nav.generating': 'Génération...',
    'nav.generateFichePlan': 'Générer Fiche Plan',
    'nav.generatingPlan': 'Génération Plan...',
    'nav.generateFichePresence': 'Générer Fiche Présence',
    'nav.completePack': 'Compléter le Pack de Formation',
    'nav.completingPack': 'Finalisation du Pack...',
    
    // Step 1 - Client Selection
    'step1.title': 'SÉLECTION CLIENT',
    'step1.search': 'Rechercher par ID ou Nom...',
    'step1.addClient': 'Ajouter un Nouveau Client',
    'step1.newClient': 'Nouveau Client',
    'step1.companyName': 'Nom de l\'Entreprise',
    'step1.matriculeFiscal': 'Matricule Fiscal',
    'step1.address': 'Adresse',
    'step1.phone': 'Téléphone',
    'step1.contactInfo': 'Informations de Contact',
    'step1.selectClient': 'Sélectionner Client:',
    'step1.selectPlaceholder': '-- Sélectionner un client --',
    'step1.clientName': 'Nom du Client:',
    'step1.clientId': 'ID Client:',
    'step1.selectToContinue': 'Sélectionnez un client pour continuer',
    'step1.searchOrAdd': 'Rechercher par ID/Nom ou ajouter un nouveau client',
    'step1.clientsFound': 'client(s) trouvé(s)',
    'step1.fillRequired': 'Veuillez remplir le Nom et le Matricule Fiscal',
    'step1.clientAdded': '✅ Client ajouté avec succès!',
    'step1.loading': 'Chargement des clients...',
    'step1.noClientsFound': 'Aucun client trouvé correspondant à:',
    'step1.matriculeFiscal': 'Matricule Fiscal',
    'step1.fillRequired': 'Veuillez remplir le Nom et le Matricule Fiscal',
    'step1.clientAdded': '✅ Client ajouté avec succès!',
    'step1.loading': 'Chargement des clients...',
    'step1.noClientsFound': 'Aucun client trouvé correspondant à:',
    'step1.matriculeFiscal': 'Matricule Fiscal',
    
    // Step 2 keys
    'step2.title': 'TYPE D\'INTERVENTION',
    'step2.selectType': 'Sélectionner le type d\'intervention',
    'step2.formations': 'Formations',
    'step2.allSoftware': 'Tous les Logiciels',
    'step2.selectFormations': 'Sélectionner une ou plusieurs formations',
    'step2.selected': 'formation(s) sélectionnée(s)',
    'step2.unsavedChanges': '⚠️ Modifications non enregistrées',
    'step2.customFormation': 'Personnalisé',
    'step2.editAllFields': 'Formation personnalisée - Tous les champs modifiables',
    'step2.templateModify': 'Modèle - Vous pouvez modifier et enregistrer comme nouveau',
    'step2.saveChanges': 'Enregistrer les Modifications?',
    'step2.saveMessage': 'Vous avez modifié cette formation. Que voulez-vous faire?',
    'step2.saveAsNew': 'Enregistrer comme Nouvelle Formation',
    'step2.useWithoutSaving': 'Utiliser Sans Enregistrer',
    'step2.formationSaved': 'Formation enregistrée avec succès!',
    'step2.changesDiscarded': 'Modifications annulées',
    'step2.saveNote': '* L\'enregistrement crée une nouvelle formation personnalisée avec vos modifications',
    'step2.license': 'Licences',
    'step2.licenseInfo': 'Sélectionner une ou plusieurs licences à installer',
    'step2.unsavedWarning': 'Vous avez des modifications non enregistrées. Continuer sans enregistrer?',
    'step2.formationOrLicense': 'Formation ou Licence',
    'step2.selectToView': 'Sélectionnez une formation pour voir et modifier les détails',
    'step2.fieldsPreFilled': 'Tous les champs sont pré-remplis mais peuvent être modifiés',
    'error.loadingFormations': 'Erreur lors du chargement des formations',
    'error.savingFormation': 'Erreur lors de l\'enregistrement de la formation',
    'step2.formationName': 'Nom de la Formation',
    'step2.reference': 'Référence',
    'step2.prerequisites': 'Prérequis',
    'step2.objectives': 'Objectifs Visés',
    'step2.competencies': 'Compétences Acquises',
    'step2.schedule': 'Programme de Formation',
    'step2.days': 'Jours',
    'step2.content': 'Contenu / Concepts',
    'step2.methods': 'Méthodes',
    'step2.addDay': 'Ajouter un Jour',
    
    // Step 3 keys (mostly already in French)
    'step3.title': 'Détails de l\'Intervention',
    'step3.nature': "Nature de l'intervention:",
    'step3.observations': 'Observations:',
    'step3.referenceBC': 'Référence BC:',
    'step3.date': "Date d'intervention:",
    'step3.intervenant': 'Intervenant(s):',
    'step3.selectIntervenant': '-- Sélectionner Intervenant --',
    'step3.location': 'Fait à (Lieu):',
    'step3.autoGenerated': '(Généré automatiquement)',
    
    // Step 4 keys
    'step4.title': 'Aperçu',
    'step4.formationTitle': "FICHE PROGRAMME D'UNE ACTION DE FORMATION",
    'step4.licenseTitle': "FICHE D'INSTALLATION",
    'step4.client': 'Client:',
    'step4.address': 'Adresse:',
    'step4.phone': 'Téléphone:',
    'step4.id': 'ID:',
    'step4.formationName': 'Nom de formation:',
    'step4.reference': 'Référence:',
    'step4.prerequisites': 'Prérequis',
    'step4.objectives': 'Objectifs visés',
    'step4.competencies': 'Compétences acquises',
    'step4.schedule': 'Programme de Formation',
    'step4.days': 'Jours',
    'step4.content': 'Contenu / Concepts',
    'step4.methods': 'Méthodes',
    'step4.duration': 'Durée (Heures)',
    'step4.theory': 'Théorie',
    'step4.practice': 'Pratique',
    'step4.totalTheory': 'Total Théorie:',
    'step4.totalPractice': 'Total Pratique:',
    'step4.total': 'Total:',
    'step4.licenseInstalled': 'Licence(s) installée(s)',
    'step4.quantity': 'Quantité',
    'step4.serialNumber': 'Numéro de série',
    'step4.invoiceNumber': 'Numéro de facture',
    'step4.noLicenses': 'Aucune licence ajoutée',
    'step4.intervenants': 'Intervenant(s)',
    'step4.interventionDate': "Date d'intervention",
    'step4.interventionNumber': "Numéro d'intervention",
    'step4.madeAt': 'Fait à :',
    'step4.clientRemarks': 'Remarques client:',
    'step4.clientSignature': 'Signature client:',
    'step4.intervenantSignature': "Signature d'intervenant:",
    'step4.date': 'Date:',
    'step4.footer': '© 2025 Sté ABBK PHYSICSWORKS.',
    'step4.preview': 'Aperçu de la Fiche',
    
    // Step 5 keys
    'step5.title': 'FICHE PLAN DE FORMATION',
    'step5.step': 'Étape 5 sur 7',
    'step5.clientSummary': 'Résumé Client',
    'step5.client': 'Client:',
    'step5.location': 'Lieu:',
    'step5.intervenant': 'Intervenant:',
    'step5.formationsPlanning': 'Planification des Formations',
    'step5.addFormation': 'Ajouter Formation',
    'step5.formation': 'Formation',
    'step5.formateur': 'Formateur',
    'step5.nombreJours': 'Nombre de jours',
    'step5.duree': 'Durée',
    'step5.lieu': 'Lieu',
    'step5.dateDebut': 'Date début',
    'step5.dateFin': 'Date fin',
    'step5.heures': 'Heures',
    'step5.details': 'Détails',
    'step5.note': 'Note :',
    'step5.contactNote': 'Note de Contact:',
    'step5.dateLe': 'Date Le :',
    'step5.signature': 'Signature',
    'step5.signatureABBK': 'Signature ABBK PHYSICSWORKS',
    'step5.subtitle': 'Étape 5 sur 7',
    
    // Step 6 keys
    'step6.title': 'FICHE DE PRÉSENCE',
    'step6.step': 'Étape 6 sur 7',
    'step6.entreprise': 'Entreprise :',
    'step6.theme': 'Thème de formation :',
    'step6.periode': 'Période de formation :',
    'step6.heure': 'Heure de formation :',
    'step6.cadre': 'Cadre de formation :',
    'step6.nombreJours': 'Nombre de jours de formation (max 7) :',
    'step6.lieu': 'Lieu de formation :',
    'step6.formateur': 'Formateur :',
    'step6.duree': 'Durée de la formation :',
    'step6.mode': 'Mode de formation :',
    'step6.participants': 'Liste des participants',
    'step6.addParticipant': 'Ajouter Participant',
    'step6.nomPrenom': 'Nom et Prénom',
    'step6.etablissement': 'Établissement / Entreprise',
    'step6.jours': 'Jours',
    'step6.details': 'Détails',
    'step6.formateur': 'Formateur:',
    'step6.note': 'Note :',
    'step6.dateLe': 'Date Le :',
    'step6.signature': 'Signature',
    'step6.signatureFormateur': 'Signature de Formateur',
    'step6.signatureABBK': 'Signature ABBK PHYSICSWORKS',
    
    // Step 7 keys
    'step7.title': "FICHE D'ÉVALUATION",
    'step7.subtitle': 'DES PARTICIPANTS',
    'step7.step': 'Étape 7 sur 7 - Dernière Étape!',
    'step7.theme': 'Thème de formation :',
    'step7.periode': 'Période de formation :',
    'step7.duree': 'Durée de la formation :',
    'step7.formateur': 'Formateur :',
    'step7.participants': 'Liste des participants',
    'step7.infoNiveau': 'Informations sur le Niveau',
    'step7.niveauInitial': 'Niveau Initial',
    'step7.connaissances': 'Connaissances théoriques',
    'step7.competencesPratiques': 'Compétences pratiques',
    'step7.participation': 'Participation et engagement',
    'step7.niveauParticipation': 'Niveau de participation active',
    'step7.contribution': 'Contribution aux discussions',
    'step7.comprehension': 'Compréhension du contenu',
    'step7.bonneComprehension': 'A démontré une bonne compréhension',
    'step7.capaciteAppliquer': 'Capacité à appliquer les connaissances',
    'step7.niveauCompetences': 'Niveau des compétences techniques acquises pendant la formation',
    'step7.attitude': 'Attitude générale pendant la formation',
    'step7.ponctuel': 'Le participant a-t-il été ponctuel et assidu',
    'step7.amelioration': 'A montré une amélioration significative pendant la formation',
    'step7.noteGeneral': 'Note Général',
    'step7.note': 'Note :',
    'step7.dateLe': 'Date Le :',
    'step7.signatureFormateur': 'Signature de Formateur',
    'step7.signatureABBK': 'Signature ABBK PHYSICSWORKS',
    
    // Saved Page
    'saved.title': 'Fiches Enregistrées',
    'saved.found': 'fiches trouvées',
    'saved.refresh': 'Actualiser',
    'saved.search': 'Rechercher par nom de client, ID ou nom de fichier...',
    'saved.allTypes': 'Tous les Types',
    'saved.formationOnly': 'Formation Seulement',
    'saved.licenseOnly': 'Licence Seulement',
    'saved.loading': 'Chargement des fiches...',
    'saved.noFiches': 'Aucune fiche trouvée',
    'saved.tryAdjusting': 'Essayez d\'ajuster votre recherche ou vos filtres',
    'saved.createFirst': 'Créez votre première fiche pour commencer!',
    'saved.formation': 'Formation',
    'saved.license': 'Licence',
    'saved.formations': 'Formations:',
    'saved.licenses': 'Licences:',
    'saved.edit': 'Modifier',
    'saved.delete': 'Supprimer la fiche',
    'saved.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette fiche?',
    
    // Common
    'common.client': 'Client',
    'common.address': 'Adresse',
    'common.phone': 'Téléphone',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.close': 'Fermer',
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.required': 'requis',
    
    // Errors
    'error.fillRequired': 'Veuillez compléter tous les champs obligatoires',
    'error.fixErrors': 'Veuillez corriger les erreurs avant de continuer',
    'error.selectClient': 'Veuillez sélectionner un client dans la liste',
    'error.selectType': 'Veuillez sélectionner le type d\'intervention (Formation ou Licence)',
    'error.enterReference': 'Veuillez entrer la Référence BC',
    'error.selectDate': 'Veuillez sélectionner la date d\'intervention',
    'error.selectIntervenant': 'Veuillez sélectionner un intervenant',
    'error.enterLocation': 'Veuillez entrer le lieu (Fait à)',
    'error.fillFormationName': 'Veuillez remplir au moins un nom de formation',
    'nav.continueTo': 'Continuer vers',
    'nav.saveFinish': 'Enregistrer & Terminer Plus Tard',
    'nav.continueFromSaved': 'Vous pouvez continuer ce pack depuis la page Enregistrés',
    'common.generated': 'Généré',

'step1.noAddPermission': 'Vous ne pouvez pas ajouter de nouveaux clients. Contactez un administrateur.',
'step2.noSavePermission': 'Vous pouvez modifier les formations pour votre fiche, mais vous ne pouvez pas les enregistrer de façon permanente. Contactez un administrateur.',
'permissions.noAccess': 'Vous n\'avez pas la permission d\'effectuer cette action.',
'permissions.adminRequired': 'Accès administrateur requis.',
'permissions.superadminRequired': 'Accès superadmin requis.',
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem('language');
    return saved || 'fr'; // Default to French
  });

  const [isTranslating, setIsTranslating] = useState(false);

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const toggleLanguage = async () => {
    const newLang = language === 'en' ? 'fr' : 'en';
    setLanguage(newLang);
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ 
      language, 
      toggleLanguage, 
      t,
      isTranslating,
      setIsTranslating
    }}>
      {children}
    </LanguageContext.Provider>
  );
};