import React, { useEffect, useState } from 'react';
import { useFormContext } from '../context/FormContext';
import { generateInterventionNature } from '../utils/mockData';
import { getAllIntervenants } from '../services/supabaseService';
import { ABBK_COLORS } from '../utils/theme';
import { useLanguage } from '../context/LanguageContext';

export default function Step3CommonDetails() {
  const { t } = useLanguage();
  const { formData, updateFormData } = useFormContext();
  const [intervenants, setIntervenants] = useState([]);
  const [loading, setLoading] = useState(true);
  const isLicenseMode = formData.interventionType === 'license';

  useEffect(() => {
    loadIntervenants();
  }, []);

  const loadIntervenants = async () => {
    try {
      setLoading(true);
      const data = await getAllIntervenants();
      setIntervenants(data);
    } catch (error) {
      console.error('Error loading intervenants:', error);
    } finally {
      setLoading(false);
    }
  };

  // Auto-fill nature and observations ONLY for license mode
  useEffect(() => {
    if (isLicenseMode && formData.licenses && formData.clientName) {
      const natureText = generateInterventionNature(formData.licenses, formData.clientName);
      updateFormData({
        interventionNature: natureText,
        observations: natureText
      });
    } else if (!isLicenseMode) {
      // Clear nature and observations for formation mode
      updateFormData({
        interventionNature: '',
        observations: ''
      });
    }
  }, [formData.licenses, formData.clientName, isLicenseMode]);

  if (loading) {
    return (
      <div className="flex items-center justify-center py-8">
        <div 
          className="animate-spin rounded-full h-8 w-8 border-b-2"
          style={{ borderColor: ABBK_COLORS.red }}
        ></div>
      </div>
    );
  }

  return (
    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-lg p-8 transition-colors duration-300">
      <h2 className="text-2xl font-bold text-gray-800 dark:text-white mb-6">{t('step3.title')}</h2>
      
      <div className="space-y-6">
        {/* Nature and Observations - ONLY for License mode */}
        {isLicenseMode && (
          <>
            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('step3.nature')}
                <span className="text-xs text-gray-500 dark:text-gray-400 ml-2">{t('step3.autoGenerated')}</span>
              </label>
              <textarea
                placeholder={t('step3.naturePlaceholder') || "Describe the intervention"}
                value={formData.interventionNature}
                onChange={(e) => updateFormData({ interventionNature: e.target.value })}
                readOnly
                rows="3"
                className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 transition-colors duration-300"
                style={{ focusRingColor: ABBK_COLORS.red }}
              />
            </div>

            <div>
              <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                {t('step3.observations')}
                <span className="text-xs text-gray-500 dark:text-gray-400 ml-2">{t('step3.autoGenerated')}</span>
              </label>
              <textarea
                placeholder={t('step3.observationsPlaceholder') || "Additional notes or observations"}
                value={formData.observations}
                onChange={(e) => updateFormData({ observations: e.target.value })}
                readOnly
                rows="4"
                className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-gray-50 dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 transition-colors duration-300"
                style={{ focusRingColor: ABBK_COLORS.red }}
              />
            </div>
          </>
        )}

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t('step3.referenceBC')}
            </label>
            <input
              type="text"
              placeholder={t('step3.referencePlaceholder') || "Reference BC"}
              value={formData.referenceBC}
              onChange={(e) => updateFormData({ referenceBC: e.target.value })}
              className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 transition-colors duration-300"
              style={{ focusRingColor: ABBK_COLORS.red }}
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              {t('step3.date')}
            </label>
            <input
              type="date"
              value={formData.interventionDate}
              onChange={(e) => updateFormData({ interventionDate: e.target.value })}
              className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 transition-colors duration-300"
              style={{ focusRingColor: ABBK_COLORS.red }}
            />
          </div>
        </div>

        {/* Intervenant Dropdown - Now from Supabase */}
        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('step3.intervenant')}
          </label>
          <select
            value={formData.intervenant}
            onChange={(e) => updateFormData({ intervenant: e.target.value })}
            className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 transition-colors duration-300"
            style={{ focusRingColor: ABBK_COLORS.red }}
          >
            <option value="">{t('step3.selectIntervenant')}</option>
            {intervenants.map((intervenant) => (
              <option key={intervenant.id} value={intervenant.name}>
                {intervenant.name}
              </option>
            ))}
          </select>
          <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
            Main intervenant (individual days can have different intervenants in Step 2)
          </p>
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
            {t('step3.location')}
          </label>
          <input
            type="text"
            placeholder={t('step3.locationPlaceholder') || "e.g., Ariana, Tunis"}
            value={formData.location}
            onChange={(e) => updateFormData({ location: e.target.value })}
            className="w-full px-4 py-3 border border-gray-300 dark:border-gray-600 rounded-lg bg-white dark:bg-gray-700 text-gray-900 dark:text-white focus:ring-2 transition-colors duration-300"
            style={{ focusRingColor: ABBK_COLORS.red }}
          />
        </div>
      </div>
    </div>
  );
}